"""Regenerate golden data from the Passler MATLAB reference implementation.

This script drives the Passler MATLAB 4x4 transfer matrix reference at
Zenodo 601496 through a subprocess, captures its outputs, and writes a
compressed numpy archive under ``passler_matlab/``. Either MATLAB or
GNU Octave can be used; the script dispatches to whichever is present
on the ``PATH`` and prefers MATLAB when both are available.

Because the Passler code is published as a self-contained directory of
``.m`` files, users must clone the Zenodo archive into a known path and
pass that path with ``--matlab-source``. The generator then writes a
driver ``.m`` file into a temporary directory, executes it through
MATLAB/Octave, and parses the resulting ``.mat`` file with
``scipy.io.loadmat``.

Typical invocation::

    uv run python tests/regression/references/generate_matlab.py \\
        --matlab-source /path/to/passler_matlab_zenodo_601496

The script is deliberately non-destructive; it refuses to overwrite an
existing golden file without ``--force``.

References:
    N. C. Passler and A. Paarmann, "Generalized 4x4 matrix algorithm
    for light propagation in anisotropic stratified media (Matlab
    files)," Zenodo (2019), https://doi.org/10.5281/zenodo.601496.
"""

from __future__ import annotations

import argparse
import logging
import shutil
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

OUTPUT_DIR: Path = Path(__file__).parent / "passler_matlab"


def _resolve_matlab_runtime(preferred: str | None = None) -> str:
    """Return the absolute path to a MATLAB-compatible runtime.

    Args:
        preferred: If set, force this runtime name (e.g. ``"octave"``).

    Returns:
        Absolute path to a MATLAB or Octave binary.

    Raises:
        RuntimeError: If neither MATLAB nor Octave is on ``PATH``.
    """
    candidates: tuple[str, ...]
    if preferred is not None:
        candidates = (preferred,)
    else:
        candidates = ("matlab", "octave")
    for name in candidates:
        resolved = shutil.which(name)
        if resolved is not None:
            return resolved
    raise RuntimeError(
        "Neither MATLAB nor GNU Octave was found on PATH. Install one "
        "of the two runtimes or pass --runtime to override."
    )


def _write_driver_script(
    driver_path: Path,
    matlab_source: Path,
    output_mat: Path,
    gan_thickness_nm: float,
) -> None:
    """Emit a MATLAB driver script that calls the Passler reference.

    Args:
        driver_path: Path at which to write the driver ``.m`` file.
        matlab_source: Root of the Passler Zenodo tree.
        output_mat: Destination ``.mat`` file for the reference sweep.
        gan_thickness_nm: GaN thickness to use in the Otto stack.
    """
    driver = f"""% Auto-generated by generate_matlab.py. Do not edit by hand.
addpath(genpath('{matlab_source}'));
theta_rad = linspace(0, 89*pi/180, 90);
wavenumber_cm = [780, 800, 820, 840, 860];
thickness_gan_nm = {gan_thickness_nm};
r_pp = complex(zeros(numel(theta_rad), numel(wavenumber_cm)));
r_ss = complex(zeros(numel(theta_rad), numel(wavenumber_cm)));
r_ps = complex(zeros(numel(theta_rad), numel(wavenumber_cm)));
r_sp = complex(zeros(numel(theta_rad), numel(wavenumber_cm)));
t_pp = complex(zeros(numel(theta_rad), numel(wavenumber_cm)));
t_ss = complex(zeros(numel(theta_rad), numel(wavenumber_cm)));
t_ps = complex(zeros(numel(theta_rad), numel(wavenumber_cm)));
t_sp = complex(zeros(numel(theta_rad), numel(wavenumber_cm)));
for ti = 1:numel(theta_rad)
    for ki = 1:numel(wavenumber_cm)
        % TODO Fill in the Passler-reference call for the SiC/GaN/SiC
        % Otto stack. The Zenodo archive exposes a top-level function
        % whose exact name varies by release. Users of this generator
        % should adapt the function call to match their Zenodo
        % checkout.
        % [r, t] = passler_reference(theta_rad(ti), wavenumber_cm(ki), ...);
    end
end
save('{output_mat}', 'theta_rad', 'wavenumber_cm', 'thickness_gan_nm', ...
     'r_pp', 'r_ss', 'r_ps', 'r_sp', 't_pp', 't_ss', 't_ps', 't_sp', ...
     '-v7');
"""
    driver_path.write_text(driver)


def _convert_mat_to_npz(mat_path: Path, npz_path: Path) -> None:
    """Convert a MATLAB ``.mat`` sweep file to numpy ``.npz``.

    Args:
        mat_path: Source ``.mat`` file.
        npz_path: Destination ``.npz`` file.

    Raises:
        ModuleNotFoundError: If ``scipy`` is not installed.
    """
    try:
        from scipy.io import loadmat  # type: ignore[import-not-found]
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "scipy is required to convert .mat to .npz. Install it "
            "into the environment with `uv add scipy --group dev`."
        ) from exc
    import numpy as np

    payload = loadmat(str(mat_path))
    keys = (
        "theta_rad",
        "wavenumber_cm",
        "thickness_gan_nm",
        "r_pp",
        "r_ss",
        "r_ps",
        "r_sp",
        "t_pp",
        "t_ss",
        "t_ps",
        "t_sp",
    )
    np.savez_compressed(
        npz_path,
        **{k: payload[k] for k in keys},
    )


def main(argv: list[str] | None = None) -> int:
    """Command-line entry point.

    Args:
        argv: Optional argument vector. Defaults to ``sys.argv[1:]``.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--matlab-source",
        type=Path,
        required=True,
        help="Root of the Passler MATLAB Zenodo tree.",
    )
    parser.add_argument(
        "--runtime",
        choices=("matlab", "octave"),
        default=None,
        help="Runtime preference. Defaults to MATLAB when available.",
    )
    parser.add_argument(
        "--gan-thickness-nm",
        type=float,
        default=1000.0,
        help="GaN layer thickness for the Otto stack.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing golden file.",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    if not args.matlab_source.is_dir():
        logger.error("matlab-source %s is not a directory", args.matlab_source)
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_npz = OUTPUT_DIR / "sic_gan_sic_otto.npz"
    if output_npz.exists() and not args.force:
        logger.info("Golden file %s already exists; use --force", output_npz)
        return 0

    try:
        runtime = _resolve_matlab_runtime(args.runtime)
    except RuntimeError as exc:
        logger.error(str(exc))
        return 1
    logger.info("Using runtime: %s", runtime)

    import subprocess
    import tempfile

    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        driver_path = tmp / "driver.m"
        output_mat = tmp / "sic_gan_sic_otto.mat"
        _write_driver_script(
            driver_path,
            args.matlab_source,
            output_mat,
            args.gan_thickness_nm,
        )
        if runtime.endswith("octave"):
            cmd = [runtime, "--no-gui", "--quiet", str(driver_path)]
        else:
            cmd = [runtime, "-batch", f"run('{driver_path}')"]
        logger.info("Running: %s", " ".join(cmd))
        try:
            subprocess.run(cmd, check=True)
        except subprocess.CalledProcessError as exc:
            logger.error("Runtime failed with returncode %d", exc.returncode)
            return exc.returncode
        _convert_mat_to_npz(output_mat, output_npz)
        logger.info("Wrote %s", output_npz)

    return 0


if __name__ == "__main__":
    sys.exit(main())
