#!/usr/bin/env python3
"""Compute the next semver and rewrite package version files for a release PR.

Uses git-cliff (Commitizen / conventional-commits rules via ``cliff.toml``)
to derive the bump from commits since the latest ``v*`` tag, unless an
explicit bump level is supplied.

Writes ``NEW_VERSION``, ``BRANCH``, and ``BUMP_REASON`` lines to stdout for
GitHub Actions ``GITHUB_OUTPUT`` consumption when ``--github-output`` is set.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = ROOT / "pyproject.toml"
CARGO = ROOT / "Cargo.toml"
INIT = ROOT / "src" / "refloxide" / "__init__.py"
CHANGELOG = ROOT / "CHANGELOG.md"

VERSION_RE = re.compile(
    r"^version\s*=\s*\"(\d+)\.(\d+)\.(\d+)\"\s*$",
    re.MULTILINE,
)
INIT_RE = re.compile(r'^__version__\s*=\s*"(\d+)\.(\d+)\.(\d+)"\s*$', re.MULTILINE)


def _run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=ROOT,
        check=check,
        text=True,
        capture_output=True,
    )


def _ensure_cliff() -> list[str]:
    """Return a git-cliff argv prefix (system cliff or ``uvx git-cliff``)."""
    direct = _run(["git", "cliff", "--version"], check=False)
    if direct.returncode == 0:
        return ["git", "cliff"]
    return ["uvx", "git-cliff"]


def read_pyproject_version() -> str:
    text = PYPROJECT.read_text(encoding="utf-8")
    match = VERSION_RE.search(text)
    if match is None:
        raise SystemExit(f"could not find version in {PYPROJECT}")
    return ".".join(match.groups())


def parse_semver(version: str) -> tuple[int, int, int]:
    parts = version.removeprefix("v").split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        raise SystemExit(f"invalid semver: {version!r}")
    return int(parts[0]), int(parts[1]), int(parts[2])


def format_semver(major: int, minor: int, patch: int) -> str:
    return f"{major}.{minor}.{patch}"


def bump_semver(version: str, level: str) -> str:
    major, minor, patch = parse_semver(version)
    match level:
        case "major":
            return format_semver(major + 1, 0, 0)
        case "minor":
            return format_semver(major, minor + 1, 0)
        case "patch":
            return format_semver(major, minor, patch + 1)
        case _:
            raise SystemExit(f"unknown bump level: {level!r}")


def cliff_bumped_version(cliff: list[str]) -> str | None:
    result = _run([*cliff, "--bumped-version"], check=False)
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        raise SystemExit(f"git cliff --bumped-version failed:\n{stderr}")
    out = (result.stdout or "").strip().splitlines()
    # git-cliff may print WARN lines to stderr; stdout should be the version.
    candidates = [line.strip() for line in out if line.strip().startswith("v")]
    if not candidates:
        text = (result.stdout or "").strip()
        if not text:
            return None
        candidates = [text.split()[-1]]
    raw = candidates[-1].removeprefix("v")
    parse_semver(raw)
    return raw


def replace_version_in_toml(path: Path, new_version: str) -> None:
    text = path.read_text(encoding="utf-8")
    updated, count = VERSION_RE.subn(f'version = "{new_version}"', text, count=1)
    if count != 1:
        raise SystemExit(f"failed to rewrite version in {path}")
    path.write_text(updated, encoding="utf-8")


def replace_version_in_init(path: Path, new_version: str) -> None:
    text = path.read_text(encoding="utf-8")
    updated, count = INIT_RE.subn(f'__version__ = "{new_version}"', text, count=1)
    if count != 1:
        raise SystemExit(f"failed to rewrite __version__ in {path}")
    path.write_text(updated, encoding="utf-8")


def update_changelog(cliff: list[str], new_version: str) -> str:
    """Insert a cliff-generated section for ``new_version`` under Unreleased."""
    result = _run(
        [*cliff, "--unreleased", "--tag", new_version, "--strip", "header"],
        check=True,
    )
    section = (result.stdout or "").strip()
    section = re.sub(r"\n?<!-- generated by git-cliff -->\s*$", "", section).strip()
    if not section.startswith("## ["):
        raise SystemExit(f"unexpected cliff changelog body:\n{section[:200]}")

    text = CHANGELOG.read_text(encoding="utf-8")
    if re.search(rf"^## \[{re.escape(new_version)}\]", text, re.MULTILINE):
        raise SystemExit(f"CHANGELOG already has a section for {new_version}")

    marker = "## [Unreleased]"
    if marker not in text:
        raise SystemExit("CHANGELOG.md missing ## [Unreleased] heading")

    insertion = f"{marker}\n\n{section}\n"
    # Replace the Unreleased heading once; keep any notes under it by
    # placing the new release section immediately after an empty Unreleased.
    text = text.replace(marker, insertion, 1)
    # Collapse accidental triple blank lines from empty Unreleased bodies.
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    CHANGELOG.write_text(text, encoding="utf-8")
    return section


def refresh_locks() -> None:
    cargo = _run(["cargo", "update", "-p", "refloxide"], check=False)
    if cargo.returncode != 0:
        raise SystemExit(
            "cargo update -p refloxide failed:\n"
            f"{(cargo.stderr or cargo.stdout or '').strip()}"
        )
    lock = _run(["uv", "lock"], check=False)
    if lock.returncode != 0:
        detail = (lock.stderr or lock.stdout or "").strip()
        raise SystemExit(f"uv lock failed:\n{detail}")


def write_github_output(path: Path, values: dict[str, str]) -> None:
    with path.open("a", encoding="utf-8") as handle:
        for key, value in values.items():
            if "\n" in value:
                handle.write(f"{key}<<EOF\n{value}\nEOF\n")
            else:
                handle.write(f"{key}={value}\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--bump",
        choices=("auto", "patch", "minor", "major"),
        default="auto",
        help="Bump level (default: auto via git-cliff)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the planned version without rewriting files",
    )
    parser.add_argument(
        "--github-output",
        type=Path,
        default=None,
        help="Append GITHUB_OUTPUT-compatible key/value lines",
    )
    parser.add_argument(
        "--skip-lock",
        action="store_true",
        help="Skip cargo/uv lock refresh (tests only)",
    )
    args = parser.parse_args()

    current = read_pyproject_version()
    cliff = _ensure_cliff()

    if args.bump == "auto":
        bumped = cliff_bumped_version(cliff)
        if bumped is None:
            raise SystemExit(
                "git-cliff reported no bump (no releasable commits since last tag)"
            )
        new_version = bumped
        reason = f"auto (git-cliff --bumped-version from {current})"
    else:
        new_version = bump_semver(current, args.bump)
        reason = f"manual {args.bump} from {current}"

    if parse_semver(new_version) <= parse_semver(current):
        # Allow equal only when already bumped in-tree ahead of tags and
        # cliff wants the same version; otherwise require a forward bump.
        if new_version != current:
            raise SystemExit(
                f"refusing non-forward bump: current={current} proposed={new_version}"
            )
        # If files already match the cliff target, still require a tag gap.
        tags = _run(["git", "tag", "-l", f"v{new_version}"], check=True)
        if (tags.stdout or "").strip():
            raise SystemExit(
                f"version {new_version} is already tagged; nothing to prepare"
            )

    branch = f"release/v{new_version}"
    print(f"current={current}")
    print(f"NEW_VERSION={new_version}")
    print(f"BRANCH={branch}")
    print(f"BUMP_REASON={reason}")

    notes = ""
    if not args.dry_run:
        if new_version != current:
            replace_version_in_toml(PYPROJECT, new_version)
            replace_version_in_toml(CARGO, new_version)
            replace_version_in_init(INIT, new_version)
            if not args.skip_lock:
                refresh_locks()
        notes = update_changelog(cliff, new_version)
        print("Wrote version files and CHANGELOG")
    else:
        preview = _run(
            [*cliff, "--unreleased", "--tag", new_version, "--strip", "header"],
            check=True,
        )
        notes = (preview.stdout or "").strip()
        print("dry-run: no files written")

    if args.github_output is not None:
        write_github_output(
            args.github_output,
            {
                "new_version": new_version,
                "branch": branch,
                "bump_reason": reason,
                "current_version": current,
                "notes": notes,
            },
        )


if __name__ == "__main__":
    main()
